export const TEST_IDS = {
  common: {
    cart: {
      cartItem: 'cartItem',
      cartItemName: 'cartItemName',
      cartItemPlusOne: 'cartItemPlusOne',
      cartItemMinusOne: 'cartItemMinusOne',
      cartItemCount: 'cartItemCount',
      cartItemPrice: 'cartItemPrice',
      cartSubTotal: 'cartSubTotal',
      discount: 'discount',
    },
    alert: 'alert',
    snackBar: 'snackBar',
    closeSnackbar: 'closeSnackbar',
  },
  reset: {
    resetButton: 'resetButton',
    resetSuccess: 'resetSuccess',
    resetError: 'resetError',
  },
  homepageCard: {
    useCaseTitle: 'useCaseTitle',
    useCaseDescription: 'useCaseDescription',
    useCaseIcon: 'useCaseIcon',
  },
  loanRisk: {
    monthlyInstallmentValue: 'monthlyInstallmentValue',
    submitApplication: 'submitApplication',
    name: 'name',
    surname: 'surname',
    loanValue: 'loanValue',
    monthlyIncome: 'monthlyIncome',
    loanTerm: 'loanTerm',
  },
  personalization: {
    coffeeProduct: 'coffeeProduct',
    coffeeProductPrice: 'coffeeProductPrice',
    coffeeProductName: 'coffeeProductName',
    addToCart: 'addToCart',
    search: 'search',
    searchHistoryItem: 'searchHistoryItem',
  },
  paymentFraud: {
    submitPayment: 'submitPayment',
    cardNumber: 'cardNumber',
    cardExpiration: 'cardExpiration',
    cardCvv: 'cardCvv',
    usingStolenCard: 'usingStolenCard',
    askForChargeback: 'askForChargeback',
  },
  paywall: {
    articleCard: 'articleCard',
    articleContent: 'articleContent',
    goBack: 'goBack',
  },
  couponFraud: {
    couponCode: 'couponCode',
    submitCoupon: 'submitCoupon',
  },
  webScraping: {
    search: 'search',
    card: 'card',
    originAirportCode: 'originAirportCode',
    destinationAirportCode: 'destinationAirportCode',
    price: 'price',
    departureTime: 'departureTime',
    arrivalTime: 'arrivalTime',
    airline: 'airline',
  },
  credentialStuffing: {
    login: 'login',
    password: 'password',
  },
  smsFraud: {
    phoneNumberInput: 'phoneNumberInput',
    sendMessage: 'sendMessage',
    codeInput: 'codeInput',
    sendCode: 'sendCode',
    copyCodeButton: 'copyCodeButton',
    codeInsideSnackbar: 'codeInsideSnackbar',
  },
  vpnDetection: {
    callout: 'callout',
    activateRegionalPricing: 'activateRegionalPricing',
  },
  playground: {
    agentResponseJSON: 'agentResponseJSON',
    serverResponseJSON: 'serverResponseJSON',
    refreshButton: 'refreshButton',
    jsonLink: 'jsonLink',
  },
  accountSharing: {
    usernameInput: 'usernameInput',
    passwordInput: 'passwordInput',
    loginButton: 'loginButton',
    signUpButton: 'signUpButton',
    forceLoginButton: 'forceLoginButton',
    challengeGoBackButton: 'challengeGoBackButton',
    logoutButton: 'logoutButton',
    contentCard: 'contentCard',
    switchToLoginButton: 'switchToLoginButton',
    switchToSignUpButton: 'switchToSignUpButton',
  },
} as const;

export const TEST_ATTRIBUTES = {
  id: 'data-testid',
  severity: 'data-test-severity',
};
